#:import CourseScreen views.CourseScreen
#:import DetailCourseScreen views.DetailCourseScreen

<MainScreen@MDScreen>:
    BoxLayout:
        Button:
            text: "Go to courses"
            color: 'black'
            on_press:
                root.manager.current = 'course'

MDScreenManager:
    MainScreen:
        name: 'main'
    CourseScreen:
        name: 'course'
    DetailCourseScreen:
        name: 'CurseDetails'
    